# Generated by Django 4.0.3 on 2022-03-30 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.RemoveField(
            model_name='links',
            name='league',
        ),
        migrations.RemoveField(
            model_name='links',
            name='season',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='league',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='round',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='season',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='team_home',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='team_versus',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='Matchs',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Seasons',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
