# Generated by Django 4.0.3 on 2022-03-30 10:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_panel', '0002_delete_files_remove_links_league_remove_links_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_season', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=200)),
                ('transfer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TeamProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describe', models.TextField(blank=True, max_length=2000)),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Matchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home_result', models.CharField(blank=True, max_length=10)),
                ('team_versus_result', models.CharField(blank=True, max_length=10)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('day', models.DateField(default=datetime.date(2022, 3, 30))),
                ('hour', models.TimeField(default=datetime.time)),
                ('match_info', models.TextField(default='', max_length=200)),
                ('league', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.league')),
                ('round', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.round')),
                ('season', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.season')),
                ('team_home', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_home', to='user_panel.teams')),
                ('team_versus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_versus', to='user_panel.teams')),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=300)),
                ('transfer', models.BooleanField(default=False)),
                ('last_season', models.BooleanField(default=False)),
                ('league', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.league')),
                ('season', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.season')),
            ],
        ),
        migrations.CreateModel(
            name='ActualMatchs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_home_result', models.CharField(blank=True, max_length=10)),
                ('team_versus_result', models.CharField(blank=True, max_length=10)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('day', models.DateField(default=datetime.date(2022, 3, 30))),
                ('hour', models.TimeField(default=datetime.time)),
                ('match_info', models.TextField(default='', max_length=200)),
                ('active_round', models.BooleanField(default=False)),
                ('finished_round', models.BooleanField(default=False)),
                ('live', models.BooleanField(default=False)),
                ('league', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.league')),
                ('round', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.round')),
                ('season', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.season')),
                ('team_home', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_home1', to='user_panel.teams')),
                ('team_versus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_versus2', to='user_panel.teams')),
            ],
        ),
    ]
