# Generated by Django 4.0.3 on 2022-03-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actualmatchs',
            name='league',
        ),
        migrations.RemoveField(
            model_name='actualmatchs',
            name='round',
        ),
        migrations.RemoveField(
            model_name='actualmatchs',
            name='season',
        ),
        migrations.RemoveField(
            model_name='actualmatchs',
            name='team_home',
        ),
        migrations.RemoveField(
            model_name='actualmatchs',
            name='team_versus',
        ),
        migrations.DeleteModel(
            name='ActualSeason',
        ),
        migrations.RemoveField(
            model_name='links',
            name='league',
        ),
        migrations.RemoveField(
            model_name='links',
            name='season',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='league',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='round',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='season',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='team_home',
        ),
        migrations.RemoveField(
            model_name='matchs',
            name='team_versus',
        ),
        migrations.RemoveField(
            model_name='teamprofile',
            name='team',
        ),
        migrations.DeleteModel(
            name='ActualMatchs',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.DeleteModel(
            name='Matchs',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='TeamProfile',
        ),
        migrations.DeleteModel(
            name='Teams',
        ),
    ]
