# Generated by Django 4.0.3 on 2022-03-31 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EightiesKidsTVShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('decade', models.IntegerField(default=1980)),
                ('blurb', models.TextField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='actualmatchs',
            name='day',
            field=models.DateField(default=datetime.date(2022, 3, 31)),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='day',
            field=models.DateField(default=datetime.date(2022, 3, 31)),
        ),
    ]
