# Generated by Django 4.0.3 on 2022-03-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0006_eightieskidstvshows_alter_actualmatchs_day_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EightiesKidsTVShows',
        ),
    ]
