# Generated by Django 4.0.3 on 2022-04-02 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0007_delete_eightieskidstvshows'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='blog_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='actualmatchs',
            name='day',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='day',
            field=models.DateField(default=datetime.date(2022, 4, 2)),
        ),
    ]
