# Generated by Django 4.0.3 on 2022-04-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0008_teams_blog_pic_alter_actualmatchs_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='blog_pic',
        ),
        migrations.AddField(
            model_name='teamprofile',
            name='arms_of_team',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
