# Generated by Django 4.0.3 on 2022-04-02 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0009_remove_teams_blog_pic_teamprofile_arms_of_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='arms_of_team',
            field=models.ImageField(default='images/default_arms.png', null=True, upload_to=''),
        ),
    ]
