# Generated by Django 3.2.12 on 2022-04-20 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0027_auto_20220420_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualmatchs',
            name='day',
            field=models.DateField(default=datetime.date(2022, 4, 21)),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='day',
            field=models.DateField(default=datetime.date(2022, 4, 21)),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2022, 4, 21)),
        ),
    ]
