# Generated by Django 3.2.12 on 2022-04-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0029_infoaboutround'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='promote_to',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='relegation_to',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
