# Generated by Django 3.2.12 on 2022-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0033_auto_20220424_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='stadion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
