# Generated by Django 3.2.12 on 2022-04-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0034_teamprofile_stadion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamprofile',
            old_name='stadion',
            new_name='stadium',
        ),
    ]
