# Generated by Django 3.2.12 on 2022-04-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0035_rename_stadion_teamprofile_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprofile',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
