# Generated by Django 3.2.12 on 2022-04-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0046_alter_teamprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprofile',
            name='user',
        ),
    ]
