# Generated by Django 3.2.12 on 2022-05-12 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0049_auto_20220502_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualmatchs',
            name='day',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
        migrations.AlterField(
            model_name='matchs',
            name='day',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='date_of_creation',
            field=models.DateField(default=datetime.date(2022, 5, 12)),
        ),
    ]
