# Generated by Django 3.2.12 on 2022-05-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0051_actualmatchs_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='capitan',
            field=models.CharField(blank=True, default='Nie podano', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='chairman',
            field=models.CharField(blank=True, default='Nie podano', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='coach',
            field=models.CharField(blank=True, default='Nie podano', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='colors',
            field=models.CharField(blank=True, default='Nie podano', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='stadium',
            field=models.CharField(blank=True, default='Nie podano', max_length=50, null=True),
        ),
    ]
