# Generated by Django 3.2.12 on 2022-04-18 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_panel', '0025_auto_20220418_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('entry', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_agree', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('league', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.league')),
                ('team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.teams')),
            ],
        ),
    ]
