# Generated by Django 3.2.12 on 2022-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='article_type',
            field=models.CharField(choices=[('1', 'artykul sponsorowany'), ('2', 'artykul nie sponsorowany')], max_length=100, null=True),
        ),
    ]
