# Generated by Django 3.2.12 on 2022-04-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogentry_article_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogentry',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='league',
        ),
        migrations.RemoveField(
            model_name='blogentry',
            name='team',
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
