# Generated by Django 3.2.12 on 2022-04-18 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0025_auto_20220418_1519'),
        ('blog', '0003_auto_20220418_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='league',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_panel.league'),
        ),
    ]
