# Generated by Django 3.2.12 on 2022-04-19 20:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_entrycomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='entry',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
