# Generated by Django 3.2.12 on 2022-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogentry_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='article_type',
            field=models.CharField(choices=[('1', 'Artykul sponsorowany'), ('2', 'Artykul nie sponsorowany')], default='2', max_length=100, null=True),
        ),
    ]
