# Generated by Django 3.2.12 on 2022-04-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_blogentry_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
