# Generated by Django 3.2.12 on 2022-04-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogentry_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogentry',
            name='publicate_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
