# Generated by Django 3.2.12 on 2022-04-24 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogentry_publicate_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='publicate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
