# Generated by Django 3.2.12 on 2022-04-17 09:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_panel', '0024_auto_20220417_1119'),
        ('live_matches', '0002_auto_20220417_1119'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coments',
            new_name='Coment',
        ),
    ]
