# Generated by Django 3.2.12 on 2022-04-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_matches', '0004_rename_coment_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EightiesKidsTVShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('decade', models.IntegerField(default=1980)),
                ('blurb', models.TextField()),
                ('url', models.URLField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
