# Generated by Django 3.2.12 on 2022-04-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_matches', '0005_eightieskidstvshows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EightiesKidsTVShows',
        ),
    ]
