# Generated by Django 3.2.12 on 2022-05-12 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0050_auto_20220512_0917'),
        ('live_matches', '0006_delete_eightieskidstvshows'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_team_home', models.IntegerField()),
                ('result_team_versus', models.IntegerField()),
                ('time_of_edit', models.DateTimeField(auto_now_add=True)),
                ('accept', models.BooleanField(default=False)),
                ('league', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.league')),
                ('season', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user_panel.season')),
                ('t_one', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='t_one', to='user_panel.teams')),
                ('t_two', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='t_two', to='user_panel.teams')),
            ],
        ),
    ]
