# Generated by Django 3.2.12 on 2022-05-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0050_auto_20220512_0917'),
        ('live_matches', '0008_auto_20220512_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='editresult',
            name='match',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='match_sc', to='user_panel.actualmatchs'),
        ),
    ]
