# Generated by Django 3.2.12 on 2022-05-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_matches', '0010_editresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editresult',
            name='result_team_home',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='editresult',
            name='result_team_versus',
            field=models.IntegerField(default=0),
        ),
    ]
