# Generated by Django 3.2.12 on 2022-05-12 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_matches', '0011_auto_20220512_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editresult',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
