# Generated by Django 3.2.12 on 2022-05-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_matches', '0012_alter_editresult_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editresult',
            name='result_team_home',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='editresult',
            name='result_team_versus',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
