# Generated by Django 3.2.12 on 2022-05-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_matches', '0013_auto_20220512_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editresult',
            name='user',
        ),
    ]
