# Generated by Django 3.2.12 on 2022-05-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=100, null=True)),
                ('text', models.TextField(blank=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
